name: PR checks
on: [push, pull_request]

jobs:
  lint:
      name: Check commits
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              fetch-depth: 0

        - uses: ahmadnassri/action-commit-lint@v1
          with:
            config: conventional
          
        - name: clang-format Check
          uses: jidicula/clang-format-action@v4.10.1

