name: PR checks
on: [push, pull_request]

jobs:
  lint:
      name: Check commit message
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              fetch-depth: 0

        - uses: ahmadnassri/action-commit-lint@v1
          with:
            config: conventional
